name: CI

on: [push]

env:
  GCR_DOMAIN: eu.gcr.io
  GCR_IMAGE_API: tsumego-1575212161857/api

jobs:
  build-and-publish:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v1
      - name: Read .nvmrc
        run: echo "::set-output name=nvmrc::$(cat .nvmrc)"
        id: nvm
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: '${{ steps.nvm.outputs.nvmrc }}'
      - name: npm install, build, and test
        run: |
          yarn install --frozen-lockfile
          yarn build
          yarn test
        env:
          CI: true
      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: '270.0.0'
          service_account_email: ${{ secrets.GCP_SA_EMAIL }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
      - run: gcloud info
      - name: Login to GCR
        run: gcloud auth configure-docker
      - name: Build, tag, and push image to GCR
        env:
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $GCR_DOMAIN/$GCR_IMAGE_API:$IMAGE_TAG -f packages/api/Dockerfile .
          docker push $GCR_DOMAIN/$GCR_IMAGE_API:$IMAGE_TAG
  deploy:
    if: github.ref == 'refs/heads/master'
    needs: build-and-publish
    runs-on: ubuntu-18.04
    steps:
      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: '270.0.0'
          service_account_email: ${{ secrets.GCP_SA_EMAIL }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
      - name: Update gcloud
        run: gcloud components update
      - run: gcloud info
      - name: Login to GCR
        run: gcloud auth configure-docker
      - name: Deploy image to Cloud Run
        env:
          IMAGE_TAG: ${{ github.sha }}
        run: gcloud run deploy tsumego-api --image $GCR_DOMAIN/$GCR_IMAGE_API:$IMAGE_TAG
