name: Rate

on:
  schedule:
    - cron: '*/15 * * * *'

env:
  GCR_DOMAIN: eu.gcr.io
  GCR_IMAGE_API: tsumego-1575212161857/api
  GCLOUD_PROJECT_ID: tsumego-1575212161857

jobs:
  rate:
    runs-on: ubuntu-18.04
    steps:
      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: '274.0.1'
          service_account_email: ${{ secrets.GCP_SA_EMAIL }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
      - name: Login to GCR
        run: gcloud auth configure-docker
      - name: Install cloud sql proxy
        run: |
          wget https://dl.google.com/cloudsql/cloud_sql_proxy.linux.amd64 -O cloud_sql_proxy
          chmod +x cloud_sql_proxy
      - name: Run Rating Task
        run: |
          ./cloud_sql_proxy -instances=$GCLOUD_PROJECT_ID:europe-west1:tsumego-db=tcp:5432 &
          docker run --env DB_HOST=127.0.0.1 --env DB_PASSWORD=${{ secrets.DB_PASSWORD }} --env DB_USER=${{ secrets.DB_USER }} --env DB_NAME=tsumego --network host $GCR_DOMAIN/$GCR_IMAGE_API:deployed yarn run task:rate
